// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzuibeeoozejqifofqzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16dWliZWVvb3planFpZm9mcXpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMzE0MzIsImV4cCI6MjA2NTcwNzQzMn0.bVOrCgmHV_dEXYs8nJBQQG3x4cpdxgcOR81fKN1Zi00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);